CREATE TABLE infoprueba.dbo.BienestarAnimal_Vecino(
	id_vecino int NOT NULL IDENTITY(1,1),
	ReferenciaID INT NULL,
	documento INT NULL,
	nombre varchar(300) NULL,
	email varchar(100) NULL,
	emailAlternativo varchar(100) NULL,
	telefono varchar(100) NULL,
	telefonoAlternativo varchar(100) NULL,
	codigoPostal int NULL,
	ciudad varchar(150) NULL,
	domicilio varchar(150) NULL,
	departamento varchar(150) NULL,
	provincia varchar(150) NULL,
	pais varchar(150) NULL,
	created_at datetime DEFAULT (getdate()) NULL,
	CONSTRAINT BienestarAnimal_Vecino_PK PRIMARY KEY (id_vecino)
);
CREATE TABLE infoprueba.dbo.BienestarAnimal_Mascota(
	id_mascota INT NOT NULL IDENTITY(1,1),
	raza_id int NULL,
	tipo varchar(300) NULL,
	sexo varchar(300) NULL,
	edad varchar(300) NULL,
	tamanio varchar(300) NULL,
	peso varchar(300) NULL,
	enfermedad varchar(300) NULL,
	created_at datetime DEFAULT (getdate()) NULL,
	CONSTRAINT BienestarAnimal_Mascota_PK PRIMARY KEY (id_mascota),
	CONSTRAINT BienestarAnimal_Mascota_FK_ST_Raza FOREIGN KEY (raza_id) REFERENCES infoprueba.dbo.ST_Raza(id_raza),
);
CREATE TABLE infoprueba.dbo.BienestarAnimal_turnero(
	id_turnero int NOT NULL IDENTITY(1,1),
	delegacion_id int NULL,
	tipoMascota varchar(300) NULL,
	tipoProcedimiento VARCHAR(100) NULL,
	cantidadPreTurnos int NULL,
	totalPreTurnos int NULL,
	created_at datetime DEFAULT (getdate()) NULL,
	modified_at datetime NULL,
	deleted_at datetime NULL,
	CONSTRAINT BienestarAnimal_turnero_PK PRIMARY KEY (id_turnero),
	CONSTRAINT BienestarAnimal_turnero_FK_delegacion FOREIGN KEY (delegacion_id) REFERENCES infoprueba.dbo.delegacion(id_delegacion),
);
CREATE TABLE infoprueba.dbo.BienestarAnimal_PreTurno(
	id_preturno int NOT NULL IDENTITY(1,1),
	id_turnero int NULL,
	persona_id int NULL,
	mascota_id int NULL,
	tipoTratamiento varchar(300) NULL,
	referecia147  int NULL,
	notificado  datetime NULL,
	created_at datetime DEFAULT (getdate()) NULL,
	modified_at datetime NULL,
	deleted_at datetime NULL,
	CONSTRAINT BienestarAnimal_PreTurno_PK PRIMARY KEY (id_preturno),
	CONSTRAINT BienestarAnimal_PreTurno_FK_BienestarAnimal_Vecino FOREIGN KEY (persona_id) REFERENCES infoprueba.dbo.BienestarAnimal_Vecino(id_vecino),
	CONSTRAINT BienestarAnimal_PreTurno_FK_BienestarAnimal_turnero FOREIGN KEY (id_turnero) REFERENCES infoprueba.dbo.BienestarAnimal_turnero(id_turnero),
	CONSTRAINT BienestarAnimal_PreTurno_FK_BienestarAnimal_Mascota FOREIGN KEY (mascota_id) REFERENCES infoprueba.dbo.BienestarAnimal_Mascota(id_mascota),
);
CREATE TABLE infoprueba.dbo.BienestarAnimal_Operacion(
	id_operacion int NOT NULL IDENTITY(1,1),
	turnero_id int NULL,
	ref_usuario int NULL,
	operacion varchar(300) NULL,
	cantidad int NULL,
	created_at datetime DEFAULT (getdate()) NULL,
	modified_at datetime NULL,
	deleted_at datetime NULL,
	CONSTRAINT BienestarAnimal_Operacion_PK PRIMARY KEY (id_operacion),
	CONSTRAINT BienestarAnimal_Operacion_FK_BienestarAnimal_turnero FOREIGN KEY (turnero_id) REFERENCES infoprueba.dbo.BienestarAnimal_turnero(id_turnero),
);
